
# step1 参数 对应qwen7ab_prompt_1.py
step1:
  seed: 42
  width: [1120,2240,3360,3360]
  height: [1120,3360,2240,3360]
  model_name: "Qwen2.5-VL-72B-Instruct"
  api_key: "sk-R9_IT6ASeuOUV7TzlxUQoA"
  base_url: "https://llmapi.paratera.com/v1/"
  image_path:  "/data_C/yanglin/Qwen2.5-VL/VG-RS/images"
  question_path:  "/data_C/yanglin/Qwen2.5-VL/VG-RS/VG-RS-question.json"
  failure_json: ["/data_C/yanglin/Qwen2.5-VL/ceshi/failed_1120_1120.json","/data_C/yanglin/Qwen2.5-VL/ceshi/failed_2240_3360.json","/data_C/yanglin/Qwen2.5-VL/ceshi/failed_3360_2240.json","/data_C/yanglin/Qwen2.5-VL/ceshi/failed_3360_3360.json"]
  success_json: ["/data_C/yanglin/Qwen2.5-VL/ceshi/success_1120_1120.json","/data_C/yanglin/Qwen2.5-VL/ceshi/success_2240_3360.json","/data_C/yanglin/Qwen2.5-VL/ceshi/success_3360_2240.json","/data_C/yanglin/Qwen2.5-VL/ceshi/success_3360_3360.json"]
  success_vis_dir: ["/data_C/yanglin/Qwen2.5-VL/ceshi/success_vis_1120_1120", "/data_C/yanglin/Qwen2.5-VL/ceshi/success_vis_2240_3360","/data_C/yanglin/Qwen2.5-VL/ceshi/success_vis_3360_2240","/data_C/yanglin/Qwen2.5-VL/ceshi/success_vis_3360_3360"]
  ind: 0 # 0，1，2，3 需要执行四次，故索引形式指定每次的参数



# step2 参数 对应qwen7ab_prompt_2.py
step2:
  seed: 42
  width: [ 1120,2240,3360,3360 ]
  height: [ 1120,3360,2240,3360 ]
  model_name: "Qwen2.5-VL-72B-Instruct"
  api_key: "sk-R9_IT6ASeuOUV7TzlxUQoA"
  base_url: "https://llmapi.paratera.com/v1/"
  image_path: "/data_C/yanglin/Qwen2.5-VL/VG-RS/images"
  question_path: "/data_C/yanglin/Qwen2.5-VL/VG-RS/VG-RS-question.json"
  recored_failed_samples_json: ["/data_C/yanglin/Qwen2.5-VL/ceshi/failed_1120_1120.json","/data_C/yanglin/Qwen2.5-VL/ceshi/failed_2240_3360.json", "/data_C/yanglin/Qwen2.5-VL/ceshi/failed_3360_2240.json","/data_C/yanglin/Qwen2.5-VL/ceshi/failed_3360_3360.json"]
  failure_json: [ "/data_C/yanglin/Qwen2.5-VL/ceshi/second_failed_1120_1120.json", "/data_C/yanglin/Qwen2.5-VL/ceshi/second_failed_2240_3360.json","/data_C/yanglin/Qwen2.5-VL/ceshi/second_failed_3360_2240.json","/data_C/yanglin/Qwen2.5-VL/ceshi/second_failed_3360_3360.json" ]
  success_json: ["/data_C/yanglin/Qwen2.5-VL/ceshi/second_success_1120_1120.json","/data_C/yanglin/Qwen2.5-VL/ceshi/second_success_2240_3360.json", "/data_C/yanglin/Qwen2.5-VL/ceshi/second_success_3360_2240.json","/data_C/yanglin/Qwen2.5-VL/ceshi/second_success_3360_3360.json" ]
  success_vis_dir: ["/data_C/yanglin/Qwen2.5-VL/ceshi/second_success_vis_1120_1120","/data_C/yanglin/Qwen2.5-VL/ceshi/second_success_vis_2240_3360","/data_C/yanglin/Qwen2.5-VL/ceshi/second_success_vis_3360_2240", "/data_C/yanglin/Qwen2.5-VL/ceshi/second_success_vis_3360_3360" ]
  ind: 0 # 0，1，2，3 需要执行四次，故索引形式指定每次的参数



# step3 参数 对应merge_order.py
step3:
  base: "/data_C/yanglin/Qwen2.5-VL/VG-RS/VG-RS-question.json"
  results:
    - /data_C/yanglin/Qwen2.5-VL/ceshi/success_1120_1120.json
    - /data_C/yanglin/Qwen2.5-VL/ceshi/success_2240_3360.json
    - /data_C/yanglin/Qwen2.5-VL/ceshi/success_3360_2240.json
    - /data_C/yanglin/Qwen2.5-VL/ceshi/success_3360_3360.json
    - /data_C/yanglin/Qwen2.5-VL/ceshi/second_success_1120_1120.json
    - /data_C/yanglin/Qwen2.5-VL/ceshi/second_success_2240_3360.json
    - /data_C/yanglin/Qwen2.5-VL/ceshi/second_success_3360_2240.json
    - /data_C/yanglin/Qwen2.5-VL/ceshi/second_success_3360_3360.json
  output: "/data_C/yanglin/Qwen2.5-VL/ceshi/merged_total.json"


# step3 参数 对应dino_select.py
step4:
  json_files:
    - /data_C/yanglin/Qwen2.5-VL/VG-RS/VG-RS-question.json
    - /data_C/yanglin/Qwen2.5-VL/ceshi/success_1120_1120.json
    - /data_C/yanglin/Qwen2.5-VL/ceshi/success_2240_3360.json
    - /data_C/yanglin/Qwen2.5-VL/ceshi/success_3360_2240.json
    - /data_C/yanglin/Qwen2.5-VL/ceshi/success_3360_3360.json
    - /data_C/yanglin/Qwen2.5-VL/ceshi/second_success_1120_1120.json
    - /data_C/yanglin/Qwen2.5-VL/ceshi/second_success_2240_3360.json
    - /data_C/yanglin/Qwen2.5-VL/ceshi/second_success_3360_2240.json
    - /data_C/yanglin/Qwen2.5-VL/ceshi/second_success_3360_3360.json
  model_config: "/data_C/yanglin/Qwen2.5-VL/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py"
  model_weights: "/data_C/yanglin/Qwen2.5-VL/GroundingDINO/weights/groundingdino_swint_ogc.pth"
  root_path: "/data_C/yanglin/Qwen2.5-VL/VG-RS"
  merged_path: "/data_C/yanglin/Qwen2.5-VL/ceshi//merged_total.json"
  saved_json_path: "/data_C/yanglin/Qwen2.5-VL/ceshi/selected_results.json"

